#!/usr/bin/env bash

shopt -s globstar nullglob

echo 'finding files'
files=(./**/cache)
len=${#files[@]}
echo "found $len files"

i=0
for file in "${files[@]}"; do
	progress-bar "$i" "$len"
	echo "$file"
	(( i++ ))
done
